global using CustomExceptions.HandlerMiddleware;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using MyApp.Backend.BussinessObjects.Options;
global using MyApp.Controllers;
global using MyApp.WebApi.Configurations;
global using MyApp.WebApi.StartupExtensions;
global using System.Security.Cryptography;
